#cloud-config

runcmd:
  - [ sh, -c, "sed -i 's/1024/1024000/g; s/4096/1024000/g' /etc/sysconfig/docker" ]
  - [ sh, -c, "service docker restart"]

write_files:
  - path: /etc/ecs/ecs.config
    content: |
      ECS_CLUSTER=${cluster_name}
      ECS_RESERVED_MEMORY=${reserved_memory}
      ECS_ENABLE_SPOT_INSTANCE_DRAINING=${enable_spot_draining}