#cloud-config
repo_update: true
repo_upgrade: all
packages:
  - amazon-efs-utils
runcmd:
  - mkdir -p ${efs_directory}
  - echo "${file_system_id_01}:/ ${efs_directory} efs tls,_netdev" >> /etc/fstab
  - mount -a -t efs defaults
  - [ sh, -c, "sed -i 's/1024/1024000/g; s/4096/1024000/g' /etc/sysconfig/docker" ]
  - [ sh, -c, "service docker restart"]


write_files:
  - path: /etc/ecs/ecs.config
    content: |
      ECS_CLUSTER=${cluster_name}
      ECS_RESERVED_MEMORY=${reserved_memory}
      ECS_ENABLE_SPOT_INSTANCE_DRAINING=${enable_spot_draining}
